#pragma once

// ============================================================
// AI_FeaturePipeline.mqh
// Build feature vector in EXACT order exported from Python.
// Replace placeholders (periods, scaler arrays, feature names)
// with the values generated by your Python export report.
// ============================================================

// ------------------------------
// Exported model configuration
// ------------------------------
#define N_FEATURES 12

// Threshold and decision params copied from Python export
input double InpBuyEdgeThreshold  = 0.08;
input double InpSellEdgeThreshold = 0.08;
input double InpEdgeMargin        = 0.55;

// Optional regime tuning copied from Python config (if used)
input bool   InpUseRegimeAdjust   = true;
input double InpRegimeDelta       = 0.04;

// ------------------------------
// PLACEHOLDER SCALER ARRAYS
// Replace with Python exported scaler_main center/scale
// ------------------------------
static double g_scaler_center[N_FEATURES] = {
   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
};

static double g_scaler_scale[N_FEATURES] = {
   1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
};

// ------------------------------
// Utility: robust-safe divide
// ------------------------------
double FP_SafeDiv(const double num, const double den, const double fallback=0.0)
{
   if(MathAbs(den) < 1e-12)
      return fallback;
   return num / den;
}

// ------------------------------
// Utility: rolling mean/std over close[]
// shift = bar index where 0=current (forming), 1=last closed bar
// ------------------------------
bool FP_RollingMeanStd(const int period, const int shift, double &mean_out, double &std_out)
{
   if(period <= 1)
      return false;

   MqlRates rates[];
   int needed = shift + period + 5;
   int got = CopyRates(_Symbol, PERIOD_H1, 0, needed, rates);
   if(got < shift + period)
      return false;

   ArraySetAsSeries(rates, true);

   double sum = 0.0;
   for(int i=shift; i<shift+period; i++)
      sum += rates[i].close;

   mean_out = sum / period;

   double var = 0.0;
   for(int i=shift; i<shift+period; i++)
   {
      double d = rates[i].close - mean_out;
      var += d*d;
   }
   std_out = MathSqrt(var / period);
   return true;
}

// ------------------------------
// Utility: RSI-like ratio up-bars
// ------------------------------
double FP_UpBarRatio(const int period, const int shift)
{
   if(period <= 1)
      return 0.0;

   MqlRates rates[];
   int needed = shift + period + 2;
   int got = CopyRates(_Symbol, PERIOD_H1, 0, needed, rates);
   if(got < shift + period + 1)
      return 0.0;
   ArraySetAsSeries(rates, true);

   int up = 0;
   for(int i=shift; i<shift+period; i++)
   {
      if(rates[i].close > rates[i+1].close)
         up++;
   }
   return (double)up / (double)period;
}

// ------------------------------
// Build raw feature vector
// IMPORTANT:
// - Use shift=1 to match Python's "completed bar" signal logic
// - Keep order EXACTLY as Python export feature_names
// ------------------------------
bool FP_BuildRawFeatures(const int shift, double &feat[])
{
   ArrayResize(feat, N_FEATURES);

   MqlRates rates[];
   int got = CopyRates(_Symbol, PERIOD_H1, 0, 600, rates);
   if(got < 350)
      return false;
   ArraySetAsSeries(rates, true);

   double close0 = rates[shift].close;
   double high0  = rates[shift].high;
   double low0   = rates[shift].low;

   // Example subset features (replace with your exported set)
   // 0) ma_dev_35
   double ma35=0, sd35=0;
   if(!FP_RollingMeanStd(35, shift, ma35, sd35)) return false;
   feat[0] = FP_SafeDiv(close0, ma35, 1.0) - 1.0;

   // 1) mom_35
   feat[1] = FP_SafeDiv(close0, rates[shift+35].close, 1.0) - 1.0;

   // 2) volratio_35
   double ma105=0, sd105=0;
   if(!FP_RollingMeanStd(105, shift, ma105, sd105)) return false;
   feat[2] = FP_SafeDiv(sd35, sd105, 0.0);

   // 3) pos_35
   double hh = -DBL_MAX, ll = DBL_MAX;
   for(int i=shift; i<shift+35; i++)
   {
      if(rates[i].high > hh) hh = rates[i].high;
      if(rates[i].low  < ll) ll = rates[i].low;
   }
   feat[3] = FP_SafeDiv(close0 - ll, hh - ll, 0.5);

   // 4) rsi_like_35
   feat[4] = FP_UpBarRatio(35, shift);

   // 5) ma_dev_125
   double ma125=0, sd125=0;
   if(!FP_RollingMeanStd(125, shift, ma125, sd125)) return false;
   feat[5] = FP_SafeDiv(close0, ma125, 1.0) - 1.0;

   // 6) mom_125
   feat[6] = FP_SafeDiv(close0, rates[shift+125].close, 1.0) - 1.0;

   // 7) volratio_125
   double ma375=0, sd375=0;
   if(!FP_RollingMeanStd(375, shift, ma375, sd375)) return false;
   feat[7] = FP_SafeDiv(sd125, sd375, 0.0);

   // 8) atr_14_pct_close
   double atr = iATR(_Symbol, PERIOD_H1, 14, shift);
   feat[8] = FP_SafeDiv(atr, close0, 0.0);

   // 9) candle_body_ratio
   feat[9] = FP_SafeDiv(MathAbs(rates[shift].close - rates[shift].open), high0-low0, 0.0);

   // 10) bull_regime_score (proxy)
   feat[10] = (close0 > ma35 && ma35 > ma125) ? 1.0 : 0.0;

   // 11) bear_regime_score (proxy)
   feat[11] = (close0 < ma35 && ma35 < ma125) ? 1.0 : 0.0;

   // Finite check
   for(int k=0; k<N_FEATURES; k++)
   {
      if(!MathIsValidNumber(feat[k]))
         return false;
   }
   return true;
}

// ------------------------------
// Robust scaling in-place
// ------------------------------
bool FP_ApplyRobustScaler(double &feat[])
{
   if(ArraySize(feat) != N_FEATURES)
      return false;

   for(int i=0; i<N_FEATURES; i++)
   {
      double den = g_scaler_scale[i];
      if(MathAbs(den) < 1e-12)
         den = 1.0;
      feat[i] = (feat[i] - g_scaler_center[i]) / den;
      if(!MathIsValidNumber(feat[i]))
         return false;
   }
   return true;
}

// ------------------------------
// Build scaled model input
// ------------------------------
bool FP_BuildModelInput(const int shift, double &scaled_feat[])
{
   double raw[];
   if(!FP_BuildRawFeatures(shift, raw))
      return false;

   if(!FP_ApplyRobustScaler(raw))
      return false;

   ArrayResize(scaled_feat, N_FEATURES);
   for(int i=0; i<N_FEATURES; i++)
      scaled_feat[i] = raw[i];

   return true;
}

// ------------------------------
// Edge-threshold decision
// BUY=0, SELL=1, NO_TRADE=-1
// ------------------------------
int FP_DecideAction(double prob_buy, double prob_sell,
                    double buy_edge_threshold,
                    double sell_edge_threshold,
                    double edge_margin)
{
   double delta = prob_buy - prob_sell;

   bool buy_signal  = (delta > buy_edge_threshold)  && (prob_buy  >= edge_margin);
   bool sell_signal = (delta < -sell_edge_threshold) && (prob_sell >= edge_margin);

   if(buy_signal && !sell_signal)  return 0;
   if(sell_signal && !buy_signal)  return 1;
   return -1;
}
